# Generated by Django 4.1.4 on 2023-06-07 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('content', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='drashah',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drashah',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('public_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('subcategory', models.ManyToManyField(blank=True, to='drashos.category')),
                ('supercategory', models.ManyToManyField(blank=True, to='drashos.category')),
            ],
        ),
        migrations.AddField(
            model_name='drashah',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drashos.audiofile'),
        ),
        migrations.AddField(
            model_name='drashah',
            name='category',
            field=models.ManyToManyField(to='drashos.category'),
        ),
    ]
