# Generated by Django 4.1.4 on 2023-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0003_remove_category_public_id_remove_drashah_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drashah',
            name='category',
            field=models.ManyToManyField(blank=True, to='drashos.category'),
        ),
    ]
