# Generated by Django 4.1.4 on 2023-06-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0004_alter_drashah_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='supercategory', to='drashos.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='supercategory',
            field=models.ManyToManyField(blank=True, related_name='subcategory', to='drashos.category'),
        ),
    ]
