# Generated by Django 4.1.4 on 2023-06-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0006_alter_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='supercategory',
        ),
        migrations.CreateModel(
            name='HierarchicalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='drashos.category')),
                ('supercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supercategory', to='drashos.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='relatedCategories',
            field=models.ManyToManyField(through='drashos.HierarchicalRelationship', to='drashos.category'),
        ),
    ]
