# Generated by Django 4.1.4 on 2023-06-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0007_remove_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='relatedCategories',
            new_name='related_categories',
        ),
    ]
