# Generated by Django 4.1.4 on 2023-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drashos', '0009_remove_category_related_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supercategory',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='drashos.category'),
        ),
    ]
